import { APP_CONSTANTS } from '@/constants/app';
import { ROUTES } from '@/constants/routes';
import { AUTH_API_ENDPOINTS } from '@/modules/auth';

export const API_CLIENT_CONSTANTS = {
  BASE_URL: APP_CONSTANTS.env.API_BASE_URL,
  TIMEOUT: 10000,
  ENABLE_LOGS: true,
  LOG_IGNORED_URLS: [AUTH_API_ENDPOINTS.REFRESH],
  REFRESH_TOKEN_URL: AUTH_API_ENDPOINTS.REFRESH,
  LOGOUT_URL: AUTH_API_ENDPOINTS.LOGOUT,
  LOGOUT_REDIRECT_ROUTE: ROUTES.AUTH.LOGIN,
} as const;
